services:
  teamtasks:
    image: teamtasks
    build:
      context: .
      dockerfile: TeamTasks/Dockerfile

  teamtasks.web:
    image: teamtasks.web
    build:
      context: .
      dockerfile: TeamTasks.Web/Dockerfile

  teamtasks.tasks.api:
    image: teamtasks.tasks.api
    build:
      context: .
      dockerfile: TeamTasks.Tasks.Api/Dockerfile

  teamtasks.identity.api:
    image: teamtasks.identity.api
    build:
      context: .
      dockerfile: TeamTasks.Identity.Api/Dockerfile
      
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - 5601:5601
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ports:
      - 9200:9200
      
  redis:
    image: redis:latest
    ports:
      - 6379:6379
        
  consul:
    image: hashicorp/consul:latest
    container_name: Consul
    ports:
      - 8500:8500
  
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRES_USER: sasha
    ports:    
      - 5432:5432 
    volumes:  
      - /data/mount:/var/lib/postgresql/data 
    networks:
      - proxybackend 
        
  pg-admin:  
    image: dpage/pgadmin4:latest  
    environment:    
      - PGADMIN_DEFAULT_EMAIL=admin@mail.ru   
      - PGADMIN_DEFAULT_PASSWORD=1111    
      - PGADMIN_LISTEN_PORT=5050  
    ports:    
      - 5050:5050  
    networks:
      - proxybackend

networks:
  proxybackend:
    name: proxybackend
    driver: bridge
  elastic:
    driver: bridge

volumes:
  grafana-storage:
  elasticsearch-data:
  redis-data:
  mongodb_data:
