services:
  teamtasks:
    image: teamtasks
    build:
      context: .
      dockerfile: TeamTasks/Dockerfile

  teamtasks.web:
    image: teamtasks.web
    build:
      context: .
      dockerfile: TeamTasks.Web/Dockerfile

  teamtasks.tasks.api:
    image: teamtasks.tasks.api
    build:
      context: .
      dockerfile: TeamTasks.Tasks.Api/Dockerfile

  teamtasks.identity.api:
    image: teamtasks.identity.api
    build:
      context: .
      dockerfile: TeamTasks.Identity.Api/Dockerfile
      
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - 5601:5601
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ports:
      - 9200:9200
      
  redis:
    image: redis:latest
    ports:
      - 6379:6379

networks:
  proxybackend:
    name: proxybackend
    driver: bridge
  elastic:
    driver: bridge

volumes:
  grafana-storage:
  elasticsearch-data:
  redis-data:
  mongodb_data:
